[package]
name = "cch23-saing"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
shuttle-axum = "0.34.1"
shuttle-runtime = "0.34.1"
tokio = "1.28.2"
tracing = "0.1.40"
urlencoding = "2.1.3"
serde = "1.0.193"
serde_json = "1.0.108"
